[package]
name = "loz-cli"
version = "0.1.0"
authors = ["Haye Böhm <haye.bohm@gmail.com>"]
edition = "2018"

[dependencies]
loz-compiler = {version = "0.1.0", path="../compiler"}
clap = "3.1.18"

[[bin]]
name = "cloz"
path = "src/main.rs"