name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run unittests
      run: cargo test --verbose
    - name: Install LLVM
      run: sudo apt install llvm-9 llvm-9-dev llvm-9-runtime
    - name: Run integration tests
      run: ./test.sh
